[package]
name = "skybase-surveillance"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
config = "0.13"
serde = { version = "1.0", features = ["derive"] }